# Site settings
author: McCray Austin
title: What A Year!
header-img: img/home-bg.png
email: tubach75@hotmail.com
copyright_name: McCray Austin
description: > # this means to ignore newlines until "baseurl:"
  Twenty Twenty
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mmaustin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
